//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapAdminInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public short area_id { get; set; }
        public byte city_id { get; set; }
        public string area_swe { get; set; }
        public string area_eng { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
