//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapAdminInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icon
    {
        public Icon()
        {
            this.LocationTypes = new HashSet<LocationType>();
        }
    
        public byte icon_id { get; set; }
        public string icon_link { get; set; }
    
        public virtual ICollection<LocationType> LocationTypes { get; set; }
    }
}
