//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class kartaEntities : DbContext
    {
        public kartaEntities()
            : base("name=kartaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int usp_Area(string stad, Nullable<decimal> latitude, Nullable<decimal> longitude, string byggnad_sv, string byggnad_en)
        {
            var stadParameter = stad != null ?
                new ObjectParameter("stad", stad) :
                new ObjectParameter("stad", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(decimal));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(decimal));
    
            var byggnad_svParameter = byggnad_sv != null ?
                new ObjectParameter("byggnad_sv", byggnad_sv) :
                new ObjectParameter("byggnad_sv", typeof(string));
    
            var byggnad_enParameter = byggnad_en != null ?
                new ObjectParameter("byggnad_en", byggnad_en) :
                new ObjectParameter("byggnad_en", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Area", stadParameter, latitudeParameter, longitudeParameter, byggnad_svParameter, byggnad_enParameter);
        }
    
        public virtual int usp_insert_OldDATA(Nullable<decimal> latitud, Nullable<decimal> longitud, string ritningsnamn, string rumsnamn2, string rumsnamn3, string rumsnamn4, string byggnad_sv, string byggnad_en, Nullable<byte> vaning, string stad, string rumstyp_sv, string rumstyp_en)
        {
            var latitudParameter = latitud.HasValue ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(decimal));
    
            var longitudParameter = longitud.HasValue ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(decimal));
    
            var ritningsnamnParameter = ritningsnamn != null ?
                new ObjectParameter("ritningsnamn", ritningsnamn) :
                new ObjectParameter("ritningsnamn", typeof(string));
    
            var rumsnamn2Parameter = rumsnamn2 != null ?
                new ObjectParameter("rumsnamn2", rumsnamn2) :
                new ObjectParameter("rumsnamn2", typeof(string));
    
            var rumsnamn3Parameter = rumsnamn3 != null ?
                new ObjectParameter("rumsnamn3", rumsnamn3) :
                new ObjectParameter("rumsnamn3", typeof(string));
    
            var rumsnamn4Parameter = rumsnamn4 != null ?
                new ObjectParameter("rumsnamn4", rumsnamn4) :
                new ObjectParameter("rumsnamn4", typeof(string));
    
            var byggnad_svParameter = byggnad_sv != null ?
                new ObjectParameter("byggnad_sv", byggnad_sv) :
                new ObjectParameter("byggnad_sv", typeof(string));
    
            var byggnad_enParameter = byggnad_en != null ?
                new ObjectParameter("byggnad_en", byggnad_en) :
                new ObjectParameter("byggnad_en", typeof(string));
    
            var vaningParameter = vaning.HasValue ?
                new ObjectParameter("vaning", vaning) :
                new ObjectParameter("vaning", typeof(byte));
    
            var stadParameter = stad != null ?
                new ObjectParameter("stad", stad) :
                new ObjectParameter("stad", typeof(string));
    
            var rumstyp_svParameter = rumstyp_sv != null ?
                new ObjectParameter("rumstyp_sv", rumstyp_sv) :
                new ObjectParameter("rumstyp_sv", typeof(string));
    
            var rumstyp_enParameter = rumstyp_en != null ?
                new ObjectParameter("rumstyp_en", rumstyp_en) :
                new ObjectParameter("rumstyp_en", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_OldDATA", latitudParameter, longitudParameter, ritningsnamnParameter, rumsnamn2Parameter, rumsnamn3Parameter, rumsnamn4Parameter, byggnad_svParameter, byggnad_enParameter, vaningParameter, stadParameter, rumstyp_svParameter, rumstyp_enParameter);
        }
    }
}
